[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "2ue4ovrC4dXU5Lvea5Hxgxs1RiWLSRDm55Vn4Gm3iz2T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
